server:
  port: 8090
spring:
  application:
    name: eureka-center
  jackson:
    time-zone: GMT+8
endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  port: 8050
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false

